from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from datetime import datetime


def generate_report(
        dashboard,
        history,
        violation_folder,
        output_path):

    doc = SimpleDocTemplate(output_path)

    styles = getSampleStyleSheet()

    elements = []

    # =====================================
    # Title
    # =====================================

    elements.append(
        Paragraph(
            "<b>PPE Detection Live Monitoring Report</b>",
            styles["Title"]
        )
    )

    elements.append(Spacer(1, 20))

    # =====================================
    # Date
    # =====================================

    elements.append(

        Paragraph(

            "Generated : " +

            datetime.now().strftime("%d-%m-%Y %H:%M:%S"),

            styles["Normal"]

        )

    )

    elements.append(Spacer(1,20))

    # =====================================
    # Summary Table
    # =====================================

    table_data = [

        ["Total Detections", dashboard["total"]],

        ["SAFE", dashboard["safe"]],

        ["UNSAFE", dashboard["unsafe"]],

        ["Persons", dashboard["persons"]],

        ["Helmet Violations", dashboard["helmet"]],

        ["Vest Violations", dashboard["vest"]]

    ]

    table = Table(table_data)

    table.setStyle(

        TableStyle([

            ("BACKGROUND",(0,0),(-1,0),colors.grey),

            ("GRID",(0,0),(-1,-1),1,colors.black),

            ("BACKGROUND",(0,0),(-1,-1),colors.beige),

            ("FONTNAME",(0,0),(-1,-1),"Helvetica"),

            ("BOTTOMPADDING",(0,0),(-1,-1),8)

        ])

    )

    elements.append(table)

    elements.append(Spacer(1,20))

    # =====================================
    # Recent Detections
    # =====================================

    elements.append(

        Paragraph(

            "<b>Recent Detections</b>",

            styles["Heading2"]

        )

    )

    elements.append(Spacer(1,10))

    for row in history[:10]:

        text = (

            f"ID : {row[0]} | "

            f"Status : {row[8]} | "

            f"Persons : {row[3]} | "

            f"Date : {row[9]}"

        )

        elements.append(

            Paragraph(

                text,

                styles["Normal"]

            )

        )

    elements.append(Spacer(1,20))

    # =====================================
    # Footer
    # =====================================

    elements.append(

        Paragraph(

            "Generated by PPE Detection Live Monitoring System",

            styles["Italic"]

        )

    )

    doc.build(elements)